name: build_and_release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  releases:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    environment: build
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "cmd/paashup-cli"
        ldflags: "-X github.com/SaaShup/paashup-cli/internal/utils.VERSION=${{ github.ref }} -X github.com/SaaShup/paashup-cli/internal/utils.PLATFORM_URL=${{ vars.PLATFORM_URL }} -X github.com/SaaShup/paashup-cli/internal/utils.PLATFORM_PUB_KEY=${{ vars.PLATFORM_PUB_KEY}}"
